import { forwardRef, type ComponentProps, type ReactNode } from 'react';
import { Button } from './ui/button';
import { Tooltip, TooltipContent, TooltipTrigger } from './ui/tooltip';

/**
 * An icon-only button that cannot ship without its name (MD-100).
 *
 * DESIGN-MODERN.md asks for a tooltip on every icon-only control. The modern
 * tree had 24 of them and an `aria-label` on most — correct for a screen reader
 * and no help at all to someone looking at a row of six grey glyphs wondering
 * which one archives the card. Toby's MD-94 pass found the gap on Issues'
 * dismiss, Integrations' copy, the IDE's refresh and tab ✕, and the Triggers
 * chevron / show-secret / copy.
 *
 * Making `label` REQUIRED is the point: the name is one prop, it becomes both
 * the tooltip and the `aria-label`, and the two can no longer disagree — which
 * they already had in a couple of places where the label said one thing and the
 * title attribute another.
 *
 * This is a composition of two existing primitives, so it lives in
 * `modern/components/`, not in `components/ui/` — nothing here is generated by
 * `shadcn add` and a later `add button` cannot clobber it.
 *
 * `forwardRef` for the reason spelled out in `./ui/button.tsx` (MD-131): this
 * is itself used as `<CollapsibleTrigger asChild>` in triggers/controls.tsx,
 * and under React 18 a plain function component swallows that ref.
 */
type IconButtonProps = Omit<ComponentProps<typeof Button>, 'children' | 'aria-label'> & {
  /** The control's name. Becomes the tooltip AND the accessible name. */
  label: string;
  /** Where the tooltip sits — `left` for a control on a row's right edge. */
  side?: ComponentProps<typeof TooltipContent>['side'];
  children: ReactNode;
};

export const IconButton = forwardRef<HTMLButtonElement, IconButtonProps>(function IconButton(
  { label, side = 'top', children, size = 'icon-sm', variant = 'ghost', ...props },
  ref
) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Button ref={ref} size={size} variant={variant} aria-label={label} {...props}>
          {children}
        </Button>
      </TooltipTrigger>
      <TooltipContent side={side}>{label}</TooltipContent>
    </Tooltip>
  );
});
